# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Tests

on:
  push:
    branches:
      - 'develop'
      - 'trunk'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    strategy:
      matrix:
        php: ['8.2', '7.2']
      fail-fast: false
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer:v2
        ini-file: development
        coverage: none
      env:
        fail-fast: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Composer Cache Directory
      id: composer-cache-dir
      run: |
        echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache PHP Dependencies
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ matrix.php }}-${{ hashFiles('composer.json') }}

    - name: Install PHP Dependencies
      run: |
        composer install --prefer-dist --no-progress --no-interaction

    - name: Run the tests
      run: |
        composer test
